services:
  app:
    image: timhuang95/linkedin-impressions-app:latest
    depends_on:
      - backend
    ports:
      - "80:3000"

  backend:
    image: timhuang95/linkedin-impressions-backend:latest
    ports:
      - "4465:4465"
    volumes:
      - ./squirrels_linkedin_impressions/env.yml:/squirrels/env.yml:ro
